spring:
  datasource:
    username: "${db.username}"
    password: "${db.password}"
    url: jdbc:postgresql://${db.host}:${db.port}/${db.database}

db:
  username: "myuser"
  password: "mypassword"
  host: "localhost"
  port: 5432
  database: "mydb"
